version: '3.8'
services:
  app:
    image: cite-network
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - neo4j
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  neo4j:
    image: neo4j:4.4
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/test
      - NEO4J_dbms_security_allow__csv__import__from__file__urls=true
    volumes:
      - ./import:/import